# -*- coding: utf-8 -*-
"""AI 8 puzzle, N queen ......ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1dDErHd7lr-fzcS_Z5Udh23C35GrXNyuo
"""

import heapq
import copy

class PuzzleNode:
    def __init__(self, state, parent=None, move=None, cost=0, heuristic=0):
        self.state = state
        self.parent = parent
        self.move = move
        self.cost = cost
        self.heuristic = heuristic

    def __lt__(self, other):
        return (self.cost + self.heuristic) < (other.cost + other.heuristic)

def get_blank_position(state):
    for i in range(3):
        for j in range(3):
            if state[i][j] == 0:
                return i, j

def get_manhattan_distance(board, goal):
    distance = 0
    for i in range(3):
        for j in range(3):
            value = board[i][j]
            if value != 0:
                for row in range(3):
                    if value in goal[row]:
                        goal_row, goal_col = row, goal[row].index(value)
                        distance += abs(i - goal_row) + abs(j - goal_col)
    return distance

def get_neighbors(node, goal_state):
    neighbors = []
    blank_row, blank_col = get_blank_position(node.state)
    moves = [(0, 1), (1, 0), (0, -1), (-1, 0)]

    for move in moves:
        new_row, new_col = blank_row + move[0], blank_col + move[1]
        if 0 <= new_row < 3 and 0 <= new_col < 3:
            new_state = copy.deepcopy(node.state)
            new_state[blank_row][blank_col], new_state[new_row][new_col] = \
                new_state[new_row][new_col], new_state[blank_row][blank_col]
            neighbors.append(
                PuzzleNode(
                    state=new_state,
                    parent=node,
                    move=(blank_row, blank_col),
                    cost=node.cost + 1,
                    heuristic=get_manhattan_distance(new_state, goal_state),
                )
            )
    return neighbors

def a_star(initial_state, goal_state):
    start_node = PuzzleNode(
        state=initial_state,
        heuristic=get_manhattan_distance(initial_state, goal_state)
    )
    priority_queue = [start_node]
    visited = set()

    while priority_queue:
        current_node = heapq.heappop(priority_queue)

        if current_node.state == goal_state:
            path = []
            while current_node:
                path.append(current_node.state)
                current_node = current_node.parent
            return path[::-1]

        if tuple(map(tuple, current_node.state)) in visited:
            continue

        visited.add(tuple(map(tuple, current_node.state)))

        neighbors = get_neighbors(current_node, goal_state)
        for neighbor in neighbors:
            heapq.heappush(priority_queue, neighbor)

    return None

def print_board(board):
    for row in board:
        print(row)
    print()

if __name__ == "__main__":
    initial_state = [[2, 3, 1], [4, 5, 6], [7, 8, 0]]
    goal_state = [[1, 2, 3], [4, 5, 6], [7, 8, 0]]

    print("Initial State:")
    print_board(initial_state)

    print("Goal State:")
    print_board(goal_state)

    solution = a_star(initial_state, goal_state)

    if solution:
        print("Solution:")
        for step in solution:
            print_board(step)
    else:
        print("No solution found.")



"""### ***8 puzzle***"""

# prompt: add detailed comments on each logical turns in the above code

import heapq
import copy

class PuzzleNode:
    """
    Represents a node in the search tree for the 8-puzzle.
    """
    def __init__(self, state, parent=None, move=None, cost=0, heuristic=0):
        """
        Initializes a new PuzzleNode.

        Args:
            state: The current state of the puzzle (a 3x3 list of lists).
            parent: The parent node in the search tree.
            move: The move that led to this state.
            cost: The cost to reach this state from the initial state.
            heuristic: The estimated cost from this state to the goal state.
        """
        self.state = state
        self.parent = parent
        self.move = move
        self.cost = cost
        self.heuristic = heuristic

    def __lt__(self, other):
        """
        Compares two PuzzleNodes based on their total estimated cost (f = g + h).
        """
        return (self.cost + self.heuristic) < (other.cost + other.heuristic)

def get_blank_position(state):
    """
    Finds the position of the blank tile (0) in the puzzle state.
    """
    for i in range(3):
        for j in range(3):
            if state[i][j] == 0:
                return i, j

def get_manhattan_distance(board, goal):
    """
    Calculates the Manhattan distance heuristic for the given board.
    """
    distance = 0
    for i in range(3):
        for j in range(3):
            value = board[i][j]
            if value != 0:
                for row in range(3):
                    if value in goal[row]:
                        goal_row, goal_col = row, goal[row].index(value)
                        distance += abs(i - goal_row) + abs(j - goal_col)
    print("Total heuristic diastance = " ,distance)
    print("-------------------")
    return distance

def get_neighbors(node, goal_state):
    """
    Generates the neighboring states of the given node.
    """
    neighbors = []
    blank_row, blank_col = get_blank_position(node.state)
    moves = [(0, 1), (1, 0), (0, -1), (-1, 0)]  # Right, Down, Left, Up

    for move in moves:
        new_row, new_col = blank_row + move[0], blank_col + move[1]
        if 0 <= new_row < 3 and 0 <= new_col < 3: #check boundaries
            new_state = copy.deepcopy(node.state)
            new_state[blank_row][blank_col], new_state[new_row][new_col] = \
                new_state[new_row][new_col], new_state[blank_row][blank_col] #swap tiles
            print_board(new_state)
            neighbors.append(
                PuzzleNode(
                    state=new_state,
                    parent=node,
                    move=(blank_row, blank_col),
                    cost=node.cost + 1,
                    heuristic=get_manhattan_distance(new_state, goal_state),
                )
            )
    return neighbors

def a_star(initial_state, goal_state):
    """
    Performs the A* search algorithm to solve the 8-puzzle.
    """
    start_node = PuzzleNode(
        state=initial_state,
        heuristic=get_manhattan_distance(initial_state, goal_state)
    )
    priority_queue = [start_node]
    visited = set()

    while priority_queue:
        current_node = heapq.heappop(priority_queue) #get node with lowest cost

        if current_node.state == goal_state: #check if goal is reached
            path = []
            while current_node: #backtrack to construct path
                path.append(current_node.state)
                current_node = current_node.parent
            return path[::-1]

        if tuple(map(tuple, current_node.state)) in visited: #check if state has been visited
            continue

        visited.add(tuple(map(tuple, current_node.state)))

        neighbors = get_neighbors(current_node, goal_state)
        for neighbor in neighbors:
            heapq.heappush(priority_queue, neighbor) #add neighbors to priority queue

    return None #no solution

def print_board(board):
    """
    Prints the given board state.
    """
    for row in board:
        print(row)
    print()

if __name__ == "__main__":
    initial_state = [[1, 2, 3], [4, 5, 6], [0, 7, 8]]
    goal_state = [[1, 2, 3], [4, 5, 6], [7, 8, 0]]

    print("Initial State:")
    print_board(initial_state)

    print("Goal State:")
    print_board(goal_state)

    solution = a_star(initial_state, goal_state)

    if solution:
        print("Solution:")
        for step in solution:
            print_board(step)
    else:
        print("No solution found.")

"""N-Queens"""

# prompt: N queens problem code

def is_safe(board, row, col, n):
    print_solution(board)
    for i in range(row):
        if board[i] == col or abs(board[i] - col) == row - i:
            return False
    return True

def solve_nqueens_util(board, row, n, solutions):
    if row == n:
        solutions.append(board.copy())
        print("Found a solution...\n")
        print_solution(board)
        print("...................")
        return

    for col in range(n):
        print(row,col)
        if is_safe(board, row, col, n):
            board[row] = col
            solve_nqueens_util(board, row + 1, n, solutions)

def solve_nqueens(n):
    board = [0] * n
    solutions = []
    solve_nqueens_util(board, 0, n, solutions)
    return solutions

def print_solution(board):
    n = len(board)
    for row in range(n):
        line = ""
        for col in range(n):
            if board[row] == col:
                line += "Q "
            else:
                line += ". "
        print(line)
    print()

if __name__ == "__main__":
    print(f"Enter value of N :")
    n =  int(input()) #Change this value to solve for a different N
    solutions = solve_nqueens(n)

    print(f"Found {len(solutions)} solutions for {n}-Queens:")
    for solution in solutions:
        print_solution(solution)

"""### ***Water jug***"""

# prompt: code for water jug problem , also add code to show each steps in detail and jug

def water_jug_problem(jug1_capacity, jug2_capacity, target):
    """
    Solves the water jug problem using BFS.

    Args:
        jug1_capacity: Capacity of the first jug.
        jug2_capacity: Capacity of the second jug.
        target: The target amount of water to achieve.

    Returns:
        A list of tuples representing the steps to reach the target, or None if no solution exists.
    """

    visited = set()
    queue = [(0, 0, [])]  # (jug1_level, jug2_level, path)

    while queue:
        jug1_level, jug2_level, path = queue.pop(0)

        if jug1_level == target or jug2_level == target:
            return path + [(jug1_level, jug2_level)]

        if (jug1_level, jug2_level) in visited:
            continue
        visited.add((jug1_level, jug2_level))

        print(f"Current state: Jug 1 = {jug1_level}, Jug 2 = {jug2_level}")

        # Possible actions:
        # 1. Fill jug1
        queue.append((jug1_capacity, jug2_level, path + [(jug1_level, jug2_level)]))
        # 2. Fill jug2
        queue.append((jug1_level, jug2_capacity, path + [(jug1_level, jug2_level)]))
        # 3. Empty jug1
        queue.append((0, jug2_level, path + [(jug1_level, jug2_level)]))
        # 4. Empty jug2
        queue.append((jug1_level, 0, path + [(jug1_level, jug2_level)]))
        # 5. Pour water from jug1 to jug2
        pour_amount = min(jug1_level, jug2_capacity - jug2_level)
        queue.append((jug1_level - pour_amount, jug2_level + pour_amount, path + [(jug1_level, jug2_level)]))
        # 6. Pour water from jug2 to jug1
        pour_amount = min(jug2_level, jug1_capacity - jug1_level)
        queue.append((jug1_level + pour_amount, jug2_level - pour_amount, path + [(jug1_level, jug2_level)]))

    return None  # No solution


if __name__ == "__main__":
    jug1_capacity = 4
    jug2_capacity = 3
    target = 2

    solution = water_jug_problem(jug1_capacity, jug2_capacity, target)

    if solution:
        print("\nSolution steps:")
        for step in solution:
            print(f"Jug 1 = {step[0]}, Jug 2 = {step[1]}")
    else:
        print("No solution found.")

def display_jug_state(jug1_capacity, jug2_capacity, jug1_level, jug2_level):
    """
    Displays the current state of two jugs in the terminal.

    Parameters:
        jug1_capacity (int): Maximum capacity of Jug 1.
        jug2_capacity (int): Maximum capacity of Jug 2.
        jug1_level (int): Current water level in Jug 1.
        jug2_level (int): Current water level in Jug 2.
    """
    # Display Jug 1
    jug1_visual = "_" * jug1_level + "." * (jug1_capacity - jug1_level)
    # Display Jug 2
    jug2_visual = "_" * jug2_level + "." * (jug2_capacity - jug2_level)

    print(f"Jug 1: [{jug1_visual}] ({jug1_level}/{jug1_capacity}L)")
    print(f"Jug 2: [{jug2_visual}] ({jug2_level}/{jug2_capacity}L)")
    print("-" * 40)

# Example: Initialize jugs with 5L and 3L capacities, and start with 0L water in both jugs
jug1_capacity = 5
jug2_capacity = 3
jug1_level = 0
jug2_level = 0

# Display the initial state of the jugs
display_jug_state(jug1_capacity, jug2_capacity, jug1_level, jug2_level)

# Simulate filling Jug 1 to 5L
jug1_level = jug1_capacity
display_jug_state(jug1_capacity, jug2_capacity, jug1_level, jug2_level)

# Simulate pouring water from Jug 1 to Jug 2
pour_amount = min(jug1_level, jug2_capacity - jug2_level)
jug1_level -= pour_amount
jug2_level += pour_amount
display_jug_state(jug1_capacity, jug2_capacity, jug1_level, jug2_level)

# Simulate emptying Jug 2
jug2_level = 0
display_jug_state(jug1_capacity, jug2_capacity, jug1_level, jug2_level)

"""### Vacuum World ***Problem***"""

# prompt: code for Vacuum World Problem in  detailed

class VacuumWorld:
    def __init__(self, environment):
        self.environment = environment  # List representing the environment (e.g., ['Dirty', 'Clean'])
        self.agent_location = 0  # Initial location of the agent (0 for left, 1 for right)

    def is_clean(self):
        return all(status == 'Clean' for status in self.environment)

    def move_left(self):
        if self.agent_location == 1:
            self.agent_location = 0

    def move_right(self):
        if self.agent_location == 0:
            self.agent_location = 1

    def suck(self):
        self.environment[self.agent_location] = 'Clean'

    def print_status(self):
      print(f"Location: {'Left' if self.agent_location==0 else 'Right'}")
      print(f"Environment: {self.environment}")

    def solve(self):
        steps = []
        while not self.is_clean():
            self.print_status()

            if self.environment[self.agent_location] == 'Dirty':
                self.suck()
                steps.append("Suck")
            elif self.agent_location == 0:
                self.move_right()
                steps.append("Right")
            else:  # agent_location == 1
                self.move_left()
                steps.append("Left")
        self.print_status()  # Print the final clean environment
        return steps


if __name__ == "__main__":
    environment = ['Dirty', 'Dirty']  # Example environment: Both locations are initially dirty
    vacuum = VacuumWorld(environment)
    solution_steps = vacuum.solve()
    print("\nSolution Steps:", solution_steps)

# prompt: code for vacuum world problem simulation

# Vacuum World Problem Simulation (Improved)

class VacuumWorld:
    def __init__(self, environment):
        self.environment = environment
        self.agent_location = 0

    def is_clean(self):
        return all(status == 'Clean' for status in self.environment)

    def move_left(self):
        if self.agent_location == 1:
            self.agent_location = 0
            return True  # Indicate successful move
        return False

    def move_right(self):
        if self.agent_location == 0:
            self.agent_location = 1
            return True
        return False

    def suck(self):
        if self.environment[self.agent_location] == 'Dirty':
            self.environment[self.agent_location] = 'Clean'
            return True # Indicate successful clean
        return False

    def print_status(self):
        print(f"Location: {'Left' if self.agent_location == 0 else 'Right'}")
        print(f"Environment: {self.environment}")

    def solve(self):
        steps = []
        while not self.is_clean():
            self.print_status()
            if self.environment[self.agent_location] == 'Dirty':
                if self.suck():
                    steps.append("Suck")
            elif self.agent_location == 0:
                if self.move_right():
                    steps.append("Right")
            else:
                if self.move_left():
                  steps.append("Left")
        self.print_status()
        return steps


if __name__ == "__main__":
    # Example environment: Both locations are initially dirty
    environment = ['Dirty', 'Dirty']
    vacuum = VacuumWorld(environment)
    solution_steps = vacuum.solve()
    print("\nSolution Steps:", solution_steps)

    # Example environment: Left is clean, right is dirty
    environment = ['Clean', 'Dirty']
    vacuum = VacuumWorld(environment)
    solution_steps = vacuum.solve()
    print("\nSolution Steps:", solution_steps)
    
    
    
    # -*- coding: utf-8 -*-
"""AI state space search algorithms.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/18h8B2ygD-F_S2jWE4Q1IYA5XiyfhqzQ0

Graph traversal
"""

import networkx as nx
import matplotlib.pyplot as plt

# Graph traversal
def create_graph():
    """Creates a graph of Romanian cities and distances."""
    graph = {
        'arad': {'zerind': 75, 'timisoara': 118, 'sibiu': 140},
        'zerind': {'oradea': 71, 'arad': 75},
        'timisoara': {'lugoj': 111, 'arad': 118},
        'sibiu': {'fagaras': 99, 'oradea': 151, 'arad': 140, 'rimnicuvilcea': 80},
        'oradea': {'zerind': 71, 'sibiu': 151},
        'fagaras': {'sibiu': 99, 'bucharest': 211},
        'bucharest': {'fagaras': 211, 'pitesti': 101, 'urziceni': 85, 'giurgiu': 90},
        'pitesti': {'rimnicuvilcea': 97, 'bucharest': 101, 'craiova': 138},
        'urziceni': {'bucharest': 85, 'hirsova': 98, 'vaslui': 142},
        'giurgiu': {'bucharest': 90},
        'rimnicuvilcea': {'sibiu': 80, 'pitesti': 97, 'craiova': 146},
        'craiova': {'rimnicuvilcea': 146, 'pitesti': 138, 'drobeta': 120},
        'hirsova': {'eforie': 86, 'urziceni': 98},
        'vaslui': {'urziceni': 142, 'iasi': 92},
        'drobeta': {'mehadia': 75, 'craiova': 120},
        'eforie': {'hirsova': 86},
        'mehadia': {'drobeta': 75, 'lugoj':70},
        'lugoj': {'timisoara':111, 'mehadia':70},
        'iasi': {'neamt': 87, 'vaslui': 92},
        'neamt': {'iasi': 87}
    }
    return graph

# Create the graph
romania_map = create_graph()
print(romania_map)


# Create a NetworkX graph
graph = nx.Graph()

# Add edges with weights
for city, connections in romania_map.items():
    for neighbor, distance in connections.items():
        graph.add_edge(city, neighbor, weight=distance)

# Draw the graph
plt.figure(figsize=(12, 8))  # Adjust figure size for better visualization
pos = nx.spring_layout(graph, seed=42)  # Use spring layout for node positioning

# Draw nodes and edges
nx.draw(graph, pos, with_labels=True, node_size=500, node_color="skyblue", font_size=8, font_weight="bold", width=1.5, edge_color="gray")

# Get edge labels (weights)
edge_labels = nx.get_edge_attributes(graph, 'weight')

# Draw edge labels
nx.draw_networkx_edge_labels(graph, pos, edge_labels=edge_labels, font_size=7)

# Title and display the graph
plt.title("Romanian Map")
plt.show()

# prompt: bfs for the above graph arad  to bucharest

from collections import deque

def bfs(graph, start, goal):
    queue = deque([(start, [start])])  # Queue of (node, path)
    visited = set()

    while queue:
        (vertex, path) = queue.popleft()
        if vertex not in visited:
            if vertex == goal:
                return path
            visited.add(vertex)
            for neighbor in graph[vertex]:
                queue.append((neighbor, path + [neighbor]))
    return None  # Goal not reachable

# Example usage (assuming 'romania_map' is defined as in your previous code):
romania_map = create_graph()
start_city = 'arad'
goal_city = 'bucharest'
path = bfs(romania_map, start_city, goal_city)

if path:
    print(f"Path from {start_city} to {goal_city}: {path}")
else:
    print(f"No path found from {start_city} to {goal_city}")

# prompt: dfs for the above graph arad  to bucharest
def dfs(graph, start, goal):
    visited = set()
    stack = [(start, [start])]  # Store path along with the node

    while stack:
        (vertex, path) = stack.pop()
        if vertex not in visited:
            if vertex == goal:
                return path
            visited.add(vertex)
            for neighbor in graph[vertex]:
                if neighbor not in visited:
                    stack.append((neighbor, path + [neighbor]))
    return None  # Goal not reachable


# Example usage
romania_map = create_graph()
start_city = 'arad'
goal_city = 'bucharest'
path = dfs(romania_map, start_city, goal_city)


if path:
    print(f"Path from {start_city} to {goal_city}: {path}")
else:
    print(f"No path found from {start_city} to {goal_city}")

# prompt: uniform cost search

import heapq

def uniform_cost_search(graph, start, goal):
    """
    Performs Uniform Cost Search on a graph.

    Args:
        graph: A dictionary representing the graph where keys are nodes and values are dictionaries of neighbors with associated costs.
        start: The starting node.
        goal: The goal node.

    Returns:
        A tuple containing:
            - A list of nodes representing the shortest path from the start to the goal.
            - The total cost of the path.
        Returns (None, infinity) if no path is found.
    """
    priority_queue = [(0, start, [start])]  # (cost, node, path)
    visited = set()

    while priority_queue:
        cost, current_node, path = heapq.heappop(priority_queue)

        if current_node == goal:
            return path, cost

        if current_node in visited:
            continue

        visited.add(current_node)

        for neighbor, neighbor_cost in graph[current_node].items():
            if neighbor not in visited:
                heapq.heappush(priority_queue, (cost + neighbor_cost, neighbor, path + [neighbor]))

    return None, float('inf')  # No path found


# Example usage
romania_map = create_graph()
start_node = 'arad'
goal_node = 'bucharest'

path, cost = uniform_cost_search(romania_map, start_node, goal_node)

if path:
    print(f"Shortest path from {start_node} to {goal_node}: {path}")
    print(f"Total cost: {cost}")
else:
    print(f"No path found from {start_node} to {goal_node}")



# prompt: iterative deepening search
from collections import deque
import heapq

# ... (Your existing code for graph creation, BFS, DFS, and UCS)

def iterative_deepening_search(graph, start, goal):
    """
    Performs Iterative Deepening Search on a graph.

    Args:
        graph: A dictionary representing the graph.
        start: The starting node.
        goal: The goal node.

    Returns:
        A list representing the path from start to goal, or None if no path is found.
    """
    depth_limit = 0
    while True:
        path = depth_limited_search(graph, start, goal, depth_limit)
        if path:
            return path
        depth_limit += 1

def depth_limited_search(graph, start, goal, depth_limit):
    """
    Performs Depth-Limited Search on a graph.
    """
    visited = set()
    stack = [(start, [start], 0)]  # (node, path, depth)

    while stack:
        (vertex, path, depth) = stack.pop()

        if vertex not in visited:
            if vertex == goal:
                return path

            visited.add(vertex)

            if depth < depth_limit:
                for neighbor in graph[vertex]:
                    if neighbor not in visited:
                        stack.append((neighbor, path + [neighbor], depth + 1))
            print(path)
    return None

# Example usage
romania_map = create_graph()
start_city = 'arad'
goal_city = 'bucharest'

path = iterative_deepening_search(romania_map, start_city, goal_city)

if path:
    print(f"Path from {start_city} to {goal_city} (IDS): {path}")
else:
    print(f"No path found from {start_city} to {goal_city} (IDS)")

print("\n")

path2 = depth_limited_search(romania_map, start_city, goal_city,3)

if path2:
    print(f"Path from {start_city} to {goal_city} (DLS): {path2}")
else:
    print(f"No path found from {start_city} to {goal_city} (IDS)")
